<Project>
  <Import Project="../Directory.Build.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsTestProject)' == 'true'">
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="AwesomeAssertions.Analyzers" PrivateAssets="all" />
    <PackageReference Include="xunit.v3" />
    <Using Include="AwesomeAssertions" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
