<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Sotsera.Rafter.Analyzers</AssemblyName>
    <RootNamespace>Sotsera.Rafter.Analyzers</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
  </ItemGroup>
</Project>
